### ISSUE TITLE
CT countingObject already removed from sum

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-compare#5]
```
number-compare : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667819258563%22%2C%22timestamp%22%3A1667821069654%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: countingObject already removed from sum
Error: Assertion failed: countingObject already removed from sum
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667819258563/assert/js/assert.js:28:13)
at assert (CountingPlayAreaNode.ts:456:16)
at onNumberDragFinished (CountingPlayAreaNode.ts:90:11)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (CountingObjectNode.ts:134:30)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:510:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 4:07:38 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! I figured out that this assertion was only being hit with multitouch, and that was a valid case for the assertion to be happening. I removed the assertion and am not seeing it on CT anymore.
