### ISSUE TITLE
CT Cannot read properties of undefined (reading 'labStringProperty')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-compare#8]
```
number-compare : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671785065712%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671792381221%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671790662561%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671785457196%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671791827706%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671786309712%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-compare : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671786383616%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-compare-main.ts:59:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM
```

**Comment by pixelzoom** [comment]
I verified that this was fixed by @chrisklus in fc0fc8ec. Closing.
